library(sf)
library(terra)
library(dplyr)
library(arrow)

setwd("~/Desktop/SPHERE/NBN-LPI-forecasting/")

extract = terra::extract

# ============================================================
# 1. Load data
# ============================================================
years <- 1970:2025
uk_grid_5km <- st_read("data/uk_grid_5km.gpkg")
output_dir <- "data/env_predictors/gridded/"
uk_regions <- st_read("data/uk_regions.gpkg")
uk_1km_master <- rast(crs = "EPSG:27700", ext = ext(0, 700000, 0, 1250000), res = 1000)

# Elevation
elevation <- rast("data/env_predictors/gb_dem/uk_srtm/w001001.adf")
crs(elevation) <- "EPSG:27700"

elev_1km_mean <- resample(elevation, uk_1km_master, method = "average")
elev_1km_min   <- resample(elevation, uk_1km_master, method = "min")
elev_1km_max   <- resample(elevation, uk_1km_master, method = "max")
elev_1km_range <- elev_1km_max - elev_1km_min

elevation_1km_uk_list <- c(mean_elevation = elev_1km_mean, elevation_range = elev_1km_range)
elevation_1km_uk <- rast(elevation_1km_uk_list)


# Soil properties
soil_file_list <- list.files(path = "data/env_predictors/soil/")
soil_file_list <- paste0("data/env_predictors/soil/", soil_file_list)
soil_raster_stack <- rast(soil_file_list)

uk_bbox_wgs84 <- ext(-10, 3, 49, 61)
uk_bbox_homolosine <- project(uk_bbox_wgs84, from = "EPSG:4326", to = crs(soil_raster_stack))

soil_uk_cropped <- crop(soil_raster_stack, uk_bbox_homolosine)
soil_1km_uk <- project(soil_uk_cropped, uk_1km_master, method = "bilinear") # now 1km, EPSG:27700

#################################################################################
#LUH2 data
load("~/Desktop/luh2_data_hamonized.RData")
anthrop_layers <- rast(anthrop_layers)
# anthrop_layers <- aggregate(anthrop_layers, fact = 2, fun = mean)

nature_layers <- rast(nature_layers)
# nature_layers <- aggregate(nature_layers, fact = 2, fun = mean)

layer_years <- as.integer(gsub("X", "", names(anthrop_layers)))


# Bioclim data (COPERNICUS)
# bioclim_files = list.files("data/env_predictors/bioclim/", pattern = ".nc")
bioclim_files = list.files("/Users/alexrabeau/Desktop/SPHERE/ADAS-pest-forecasting/data/bioclim_data/2c867a29093da8fad8e3b6fcf88d895a/", pattern = ".nc")
bioclim_vars = gsub("-es_rcp45_r2i1p1_1950-2100_v1.0.nc", "", bioclim_files)

# bioclim_dir = "data/env_predictors/bioclim"
bioclim_dir = "/Users/alexrabeau/Desktop/SPHERE/ADAS-pest-forecasting/data/bioclim_data/2c867a29093da8fad8e3b6fcf88d895a"
#################################################################################


# ============================================================
# 2. Process grid
# ============================================================

grid_centres <- st_centroid(uk_grid_5km)

grid_centres <- st_transform(
  grid_centres,
  4326
)

coords <- st_coordinates(grid_centres)

grid_centres$longitude <- coords[, 1]
grid_centres$latitude  <- coords[, 2]


# ============================================================
# 3. FUNCTION TO EXTRACT A RASTER AT GRID CENTROIDS
# ============================================================

extract_raster <- function(points, raster_file, variable_name) {
  
  r <- raster_file
  
  # Convert points to terra
  pts <- terra::vect(points)
  
  # Reproject points to raster CRS
  pts <- terra::project(pts, terra::crs(r))
  
  # Extract raster values
  values <- terra::extract(r, pts)
  
  # First column is ID generated by terra
  values <- values[, -1, drop = FALSE]
  
  # If raster has one layer
  if (ncol(values) == 1) {
    
    points[[variable_name]] <- values[[1]]
    
  } else {
    
    # Multiple layers
    names(values) <- paste0(
      variable_name,
      "_",
      seq_len(ncol(values))
    )
    
    points <- bind_cols(
      points,
      values
    )
  }
  
  return(points)
}

# ============================================================
# 4. STATIC PREDICTORS
# ============================================================

static_rasters <- c(
  setNames(as.list(elevation_1km_uk), names(elevation_1km_uk)),
  setNames(as.list(soil_1km_uk), names(soil_1km_uk))
)


static_grid <- extract_raster(grid_centres, static_rasters[[1]], names(static_rasters)[1])

for (variable in names(static_rasters)[2:length(static_rasters)]) {
  
  cat("Extracting static:", variable, "\n")
  
  static_grid <- extract_raster(static_grid, static_rasters[[variable]], variable)

}


# ============================================================
# 5. DYNAMIC PREDICTORS
# ============================================================
# year = 1970

for (year in years) {
  
  cat("\nProcessing", year, "\n")

  static_grid_year = static_grid

  # ----------------------------------------------------------
  # 1. Extract bioclim to grid centroids
  # ----------------------------------------------------------
  bioclim_dir = "/Users/alexrabeau/Desktop/SPHERE/ADAS-pest-forecasting/data/bioclim_data/2c867a29093da8fad8e3b6fcf88d895a/"

  for(file in bioclim_files){
    
    bioclim_path = paste0(bioclim_dir,file)
    bioclim <- terra::rast(bioclim_path)
    bioclim_v2 <- bioclim[[grep(as.character(year), time(bioclim))]]

    bioclim_values <- terra::extract(bioclim_v2,grid_centres)
    bioclim_values <- bioclim_values[, -1, drop = FALSE]
    
    static_grid_year[[gsub("-es_rcp45_r2i1p1_1950-2100_v1.0.nc","",file)]] <- bioclim_values[[1]]
    
  }

  cat("  bioclim processed\n")
  
  # ----------------------------------------------------------
  # 2. Extract LUH2 to grid centroids
  # ----------------------------------------------------------
  
  anthrop_luh2 <- anthrop_layers[[grep(year, names(anthrop_layers))]]
  anthrop_luh2_values <- terra::extract(anthrop_luh2, grid_centres)
  anthrop_luh2_values <- anthrop_luh2_values[, -1, drop = FALSE]
  static_grid_year[["anthrop_luh2"]] <- anthrop_luh2_values[[1]]

  nature_luh2 <- nature_layers[[grep(year, names(nature_layers))]]
  nature_luh2_values <- terra::extract(nature_luh2, grid_centres)
  nature_luh2_values <- nature_luh2_values[, -1, drop = FALSE]
  static_grid_year[["nature_luh2"]] <- nature_luh2_values[[1]]
  
  cat("  LUH2 processed\n")
  
  # ----------------------------------------------------------
  # 3. Export
  # ----------------------------------------------------------
  static_grid_year_export <- static_grid_year %>% st_drop_geometry()
  static_grid_year_export <- static_grid_year_export %>% dplyr::rename('Longitude..WGS84.' = 'longitude', 
                                           'Latitude..WGS84.' = 'latitude', 
                                           'anthrop_lu' = 'anthrop_luh2', 
                                           'nature_lu' = 'nature_luh2')
  colnames(static_grid_year_export) = gsub("\\.", "-", colnames(static_grid_year_export))
  
    write.csv(static_grid_year_export, paste0(output_dir, "gridden_env_", year, ".csv"), row.names = FALSE)

}